name: Checks
on:
  - push

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7
      - id: Init
        run: terraform init -no-color
      - id: Fmt
        run: terraform fmt -check -recursive -no-color
      - id: Validate
        run: terraform validate -no-color
  tests:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@master
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}
          role-duration-seconds: 900
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7
      - uses: ./.github/actions/ruby-tests
